name: calories_tracker
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: 3.13.0
  firebase_auth: 5.5.2
  cloud_firestore: 5.6.6
  provider: 6.1.4
  http: 1.3.0
  intl: 0.19.0
  fl_chart: 0.70.2
  mobile_scanner: 6.0.7
  numberpicker: ^2.1.2
  google_fonts: 6.2.1
  flutter_localizations: # <--- Thêm dòng này
    sdk: flutter        # <--- Thêm dòng này

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
