// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCByDlxzu2LTcaj5KZsGxFigr6EReEkUqM',
    appId: '1:1085338799978:web:7c34aa2fedcacac2585f13',
    messagingSenderId: '1085338799978',
    projectId: 'calorie-tracker-app-9c0fd',
    authDomain: 'calorie-tracker-app-9c0fd.firebaseapp.com',
    storageBucket: 'calorie-tracker-app-9c0fd.firebasestorage.app',
    measurementId: 'G-SZ2SD87R1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACiakynE4xnV52l8-SsQ5Se87kneseWKc',
    appId: '1:1085338799978:android:ef31c98799f9e3a2585f13',
    messagingSenderId: '1085338799978',
    projectId: 'calorie-tracker-app-9c0fd',
    storageBucket: 'calorie-tracker-app-9c0fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy4ApofGAVVrRYR8jb4WPGf91vdPK2tUo',
    appId: '1:1085338799978:ios:1a27088da581d42b585f13',
    messagingSenderId: '1085338799978',
    projectId: 'calorie-tracker-app-9c0fd',
    storageBucket: 'calorie-tracker-app-9c0fd.firebasestorage.app',
    iosBundleId: 'com.example.caloriesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy4ApofGAVVrRYR8jb4WPGf91vdPK2tUo',
    appId: '1:1085338799978:ios:1a27088da581d42b585f13',
    messagingSenderId: '1085338799978',
    projectId: 'calorie-tracker-app-9c0fd',
    storageBucket: 'calorie-tracker-app-9c0fd.firebasestorage.app',
    iosBundleId: 'com.example.caloriesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCByDlxzu2LTcaj5KZsGxFigr6EReEkUqM',
    appId: '1:1085338799978:web:c7c340752d888368585f13',
    messagingSenderId: '1085338799978',
    projectId: 'calorie-tracker-app-9c0fd',
    authDomain: 'calorie-tracker-app-9c0fd.firebaseapp.com',
    storageBucket: 'calorie-tracker-app-9c0fd.firebasestorage.app',
    measurementId: 'G-055FKLGFB8',
  );
}
